import { Sparkles, Github } from "lucide-react";

export function Footer() {
  return (
    <footer className="border-t bg-muted/30">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
        <div className="flex flex-col items-center gap-4 text-center">
          <div className="flex items-center gap-2 text-muted-foreground">
            <Sparkles className="h-4 w-4" />
            <span className="text-sm">Auto-generated by AI</span>
          </div>
          <p className="text-sm text-muted-foreground max-w-md">
            New articles are generated automatically every day. All content is
            created using artificial intelligence for educational and
            demonstration purposes.
          </p>
          <div className="flex items-center gap-4 mt-2">
            <a
              href="https://github.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-muted-foreground transition-colors hover:text-foreground"
              data-testid="link-github"
            >
              <Github className="h-5 w-5" />
              <span className="sr-only">GitHub</span>
            </a>
          </div>
          <p className="text-xs text-muted-foreground mt-4">
            Built with React, Node.js & PostgreSQL
          </p>
        </div>
      </div>
    </footer>
  );
}
